const RESIDENTS_DB = [
    { unit: "A1", name: "Saad & Hafsat Abdulsalam" },
    { unit: "A2", name: "Chinedu Richard Nnamani" },
    { unit: "A3", name: "Enetomhe Otsemobor" },
    { unit: "A4", name: "Precious Emmanuel-Okoye" },
    { unit: "B1", name: "Opusunju Amonia" },
    { unit: "B2", name: "Isaac Yele Akintola" },
    { unit: "B3", name: "Paulinus Babatunde" },
    { unit: "B4", name: "Afolabi Laditi" },
    { unit: "C1", name: "Mr Abiodun Olatunji" },
    { unit: "C2", name: "Babajide Saba" },
    { unit: "C3", name: "Olufunmilayo Oshinbanjo" },
    { unit: "C4", name: "Babatunde Amoo" },
    { unit: "D1", name: "Mr Jerry Okoye" },
    { unit: "D2", name: "Oluwaseyi Atinaro" },
    { unit: "D3", name: "Steve Ajudua" },
    { unit: "D4", name: "IIlyas Kubau" },
    { unit: "E1", name: "Omotayo Oyewole" },
    { unit: "E2", name: "Chief Cyprian Mgbele" },
    { unit: "E3", name: "Mr & Mrs Litan" },
    { unit: "E4", name: "Oyeleye Apampa" },
    { unit: "F1", name: "Joseph Edgar" },
    { unit: "F2", name: "Mr Bola Omitogun" },
    { unit: "F3", name: "Adeyemi Adenaike" },
    { unit: "F4", name: "Anusiem Delphine Onyinye" },
    { unit: "G1", name: "Tinuola & Makanjuola Tubi" },
    { unit: "G2", name: "Mr&Mrs Femi Domingo" },
    { unit: "G3", name: "Titi Adeyemi-Doro" },
    { unit: "G4", name: "Achinike Ogheneovo" },
    { unit: "H1", name: "Bisola Ibiyeye Aderoju" },
    { unit: "H2", name: "Yvonne Okoruwa" },
    { unit: "H3", name: "Alerebo Olaolu" },
    { unit: "H4", name: "Olatoye & Morayo Edun" },
    { unit: "I1", name: "Thaddeus Aondoakaa" },
    { unit: "I2", name: "Babs Sobanjo/Edefe Ojomo" },
    { unit: "I3", name: "Rotimi & Cecilia Lawal" },
    { unit: "I4", name: "Kayode Ehizode Uduebor" },
    { unit: "J1", name: "Vincent Solomon" },
    { unit: "J2", name: "Mobolaji Omitogun" },
    { unit: "J3", name: "Mr Oluseun Osikoya" },
    { unit: "J4", name: "Ayo & Lara Olowookere" }
];
