const RESIDENTS_DB = [
    { unit: "A1", name: "SAAD & HAFSAT ABDULSALAM" },
    { unit: "A2", name: "CHINEDU RICHARD NNAMANI" },
    { unit: "A3", name: "ENETOMHE OTSEMOBOR" },
    { unit: "A4", name: "PRECIOUS EMMANUEL-OKOYE" },
    { unit: "B1", name: "OPUSUNJU AMONIA" },
    { unit: "B2", name: "ISAAC YELE AKINTOLA" },
    { unit: "B3", name: "PAULINUS BABATUNDE" },
    { unit: "B4", name: "AFOLABI LADITI" },
    { unit: "C1", name: "MR ABIODUN OLATUNJI" },
    { unit: "C2", name: "BABAJIDE SABA" },
    { unit: "C3", name: "OLUFUNMILAYO OSHINBANJO" },
    { unit: "C4", name: "BABATUNDE AMOO" },
    { unit: "D1", name: "MR JERRY OKOYE" },
    { unit: "D2", name: "OLUWASEYI ATINARO" },
    { unit: "D3", name: "STEVE AJUDUA" },
    { unit: "D4", name: "IILYAS KUBAU" },
    { unit: "E1", name: "OMOTAYO OYEWOLE" },
    { unit: "E2", name: "CHIEF CYPRIAN MGBELE" },
    { unit: "E3", name: "MR & MRS LITAN" },
    { unit: "E4", name: "OYELEYE APAMPA" },
    { unit: "F1", name: "JOSEPH EDGAR" },
    { unit: "F2", name: "MR BOLA OMITOGUN" },
    { unit: "F3", name: "ADEYEMI ADENAIKE" },
    { unit: "F4", name: "ANUSIEM DELPHINE ONYINYE" },
    { unit: "G1", name: "TINUOLA & MAKANJUOLA TUBI" },
    { unit: "G2", name: "MR&MRS FEMI DOMINGO" },
    { unit: "G3", name: "TITI ADEYEMI-DORO" },
    { unit: "G4", name: "ACHINIKE OGHENEOVO" },
    { unit: "H1", name: "BISOLA IBIYEYE ADEROJU" },
    { unit: "H2", name: "YVONNE OKORUWA" },
    { unit: "H3", name: "ALEREBO OLAOLU" },
    { unit: "H4", name: "OLATOYE & MORAYO EDUN" },
    { unit: "I1", name: "THADDEUS AONDOAKAA" },
    { unit: "I2", name: "BABS SOBANJO/EDEFE OJOMO" },
    { unit: "I3", name: "ROTIMI & CECILIA LAWAL" },
    { unit: "I4", name: "KAYODE EHIZODE UDUEBOR" },
    { unit: "J1", name: "VINCENT SOLOMON" },
    { unit: "J2", name: "MOBOLAJI OMITOGUN" },
    { unit: "J3", name: "MR OLUSEUN OSIKOYA" },
    { unit: "J4", name: "AYO & LARA OLOWOOKERE" }
];
